# Generated by Django 3.2.8 on 2021-11-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Per',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind', models.IntegerField(blank=True, null=True)),
                ('wind_dir', models.CharField(blank=True, max_length=20, null=True)),
                ('weather_con', models.CharField(blank=True, max_length=20, null=True)),
                ('temper', models.CharField(blank=True, max_length=20, null=True)),
                ('hum', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cgy', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '火灾类别表',
                'verbose_name_plural': '火灾类别表',
            },
        ),
        migrations.CreateModel(
            name='Fight_com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('person', models.CharField(blank=True, max_length=20, null=True)),
                ('see_com', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('fire_zs', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_change', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='First_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('develop', models.CharField(blank=True, max_length=20, null=True)),
                ('person', models.IntegerField(blank=True, null=True)),
                ('fire_recon', models.CharField(blank=True, max_length=20, null=True)),
                ('danger', models.CharField(blank=True, choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('fight_task', models.CharField(blank=True, max_length=20, null=True)),
                ('build_map', models.CharField(blank=True, choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=False, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lev', models.CharField(db_column='火灾等级', max_length=30)),
            ],
            options={
                'verbose_name': '火灾等级表',
                'verbose_name_plural': '火灾等级表',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('goods_pic', models.ImageField(default='', upload_to='fire')),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=15, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person_hurt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('死亡人数', models.IntegerField(blank=True, null=True)),
                ('重伤人数', models.IntegerField(blank=True, null=True)),
                ('轻伤人数', models.IntegerField(blank=True, null=True)),
                ('男性死亡人数', models.IntegerField(blank=True, null=True)),
                ('女性死亡人数', models.IntegerField(blank=True, null=True)),
                ('本地死亡人数', models.IntegerField(blank=True, null=True)),
                ('外地死亡人数', models.IntegerField(blank=True, null=True)),
                ('dead_people1', models.IntegerField(blank=True, null=True)),
                ('dead_people2', models.IntegerField(blank=True, null=True)),
                ('dead_people3', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_pic', models.ImageField(upload_to='fire')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrappedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trapped', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Save_eq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('水罐车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('泡沫水罐车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('高倍水罐车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('二氧化碳消防车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('干粉消防车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('泡沫干粉联用消防车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('登高平台消防车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('云梯消防车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('通讯消防车', models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('save_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.fight_com')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('Pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.categoryinfo')),
            ],
            options={
                'verbose_name': '火灾地点表',
                'verbose_name_plural': '火灾地点表',
            },
        ),
        migrations.CreateModel(
            name='Person_eq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('头盔', models.CharField(blank=True, max_length=20, null=True)),
                ('防护服', models.CharField(blank=True, max_length=20, null=True)),
                ('呼吸器', models.CharField(blank=True, max_length=20, null=True)),
                ('手防护', models.CharField(blank=True, max_length=20, null=True)),
                ('足防护', models.CharField(blank=True, max_length=20, null=True)),
                ('per_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.fight_com')),
            ],
        ),
        migrations.CreateModel(
            name='InjuredInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injured', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Firesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('detal_place', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('fire_type', models.CharField(blank=True, choices=[('A', 'A类'), ('B', 'B类'), ('C', 'C类'), ('D', 'D类'), ('E', 'E类'), ('F', 'F类'), ('Null', '未知')], max_length=10, null=True)),
                ('fire_level', models.CharField(blank=True, choices=[('A', '一般火灾'), ('B', '较大火灾'), ('C', '重大火灾'), ('D', '特别重大火灾'), ('Null', '未知')], max_length=10, null=True)),
                ('last_time', models.CharField(blank=True, max_length=10, null=True)),
                ('major_th', models.CharField(blank=True, max_length=20, null=True)),
                ('fire_build', models.CharField(choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=True, max_length=20)),
                ('water', models.CharField(choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=True, max_length=20)),
                ('air', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fire.air')),
            ],
        ),
        migrations.CreateModel(
            name='FireRuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=20)),
                ('call', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=20)),
                ('fire', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('trapped', models.CharField(max_length=20)),
                ('injured', models.CharField(max_length=20)),
                ('death', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
            options={
                'verbose_name': '火灾属性表',
                'verbose_name_plural': '火灾属性表',
            },
        ),
        migrations.CreateModel(
            name='Fire_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('消防人员', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('群众', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('部队', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('专家', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('政府', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('交警', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('公安', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('医疗', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('安监', models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('save_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.fight_com')),
            ],
        ),
        migrations.AddField(
            model_name='fight_com',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fire.first_team'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('fire_economic', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_cause', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_res', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_exper', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_com', models.CharField(blank=True, max_length=100, null=True)),
                ('dis_mea', models.CharField(blank=True, max_length=100, null=True)),
                ('dead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fire.person_hurt')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.TextField()),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
                ('Pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.categoryinfo')),
            ],
            options={
                'verbose_name': '火灾决策方案表',
                'verbose_name_plural': '火灾决策方案表',
            },
        ),
        migrations.CreateModel(
            name='DeathInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Build_char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_bulid', models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('old_build', models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('wuzi_ck', models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('product_cq', models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('chugq', models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('hall_build', models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True)),
                ('bfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.firesi')),
            ],
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
    ]
